version: 0.2

phases:
    install:
        runtime-versions: 
            nodejs: 14
    pre_build:
        commands:
            - echo "Logging into AWS ECR"
            - aws --version
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 100163808729.dkr.ecr.us-east-1.amazonaws.com
            - REPOSITORY_URI=100163808729.dkr.ecr.us-east-1.amazonaws.com/vinod-ecr-ml-repo
            - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    build:
        commands:
            - echo "docker build started"
            - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
            - echo "docker build completed"
    post_build:
        commands:
            - echo "push the docker image to ECR - started"
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - printf '[{"name":"vinod-ecr-ml-repo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
            - echo "push the docker image to ECR - completed"
artifacts:
    files: imagedefinitions.json
   
